version: '3.8'
services:
  mongodb:
    image: mongo:latest # Or a specific version like mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db # Persist data across container restarts
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password # Change for production
    restart: unless-stopped
  organization-api:
    build:
      context: ./organization-api
      dockerfile: Dockerfile.dev
    container_name: organization-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://admin:password@mongodb:27017/organization?authSource=admin
    volumes:
      - ./organization-api:/organization-api
    depends_on:
      - mongodb
  organization-seeder:
    build:
      context: ./organization-seeder
      dockerfile: Dockerfile.dev
    container_name: organization-seeder
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://admin:password@mongodb:27017/organization?authSource=admin
      MAIN_MANAGER_EMAIL: dejan.zivkovic90@gmail.com
      MAIN_MANAGER_RAW_PASSWORD: SomePassword123!
      MAIN_MANAGER_FIRST_NAME: Dejan
      MAIN_MANAGER_LAST_NAME: Zivkovic
    volumes:
      - ./organization-seeder:/organization-seeder
    depends_on:
      - mongodb
volumes:
  mongodb_data:
    driver: local