version: '3.8'
services:
  mongodb:
    image: mongo:latest # Or a specific version like mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db # Persist data across container restarts
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password # Change for production
    restart: unless-stopped
  store-api:
    build:
      context: ./store-api
      dockerfile: Dockerfile.dev
    container_name: store-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGO_URL: "mongodb://admin:password@mongodb:27017"
    volumes:
      - ./store-api:/store-api
    depends_on:
      - mongodb
volumes:
  mongodb_data:
    driver: local